app/chat/urls.py
from django.urls import path

from .views import room, SendMessage

app_name = "chat"
urlpatterns = [
    path("<str:room_name>/<str:user_id>/", room, name="room"),
    path("send", SendMessage.as_view(), name="send_message"),
]

app/qr_buddies/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("chat/", include("chat.urls")),
    path("dj-admin/", admin.site.urls),
    path("admin/", include("administration.urls")),
    path("", include("qr_pair.urls")),
]

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

chat/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

qr_buddies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("chat/", include("chat.urls")),
    path('admin/', admin.site.urls),
    path('', include('qr_pair.urls'))
]

app/chat/models.py
from django.db import models


class Message(models.Model):
    message = models.TextField(null=False, blank=False)
    sender = models.ForeignKey("qr_pair.QRCode", on_delete=models.CASCADE)
    sent_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"[{self.sender}]:{self.message}"

app/chat/forms.py
from django import forms

from chat.models import Message


class ChatForm(forms.ModelForm):
    message = forms.CharField(
        label="message",
        widget=forms.TextInput(
            attrs={
                "placeholder": "enter message",
                "id": "chat-message-input",
                "aria-describedby": "invalid-helper",
            }
        ),
    )

    class Meta:
        model = Message
        fields = ("message",)

app/chat/views.py
from django.http import Http404, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import FormView

from chat.auth import is_permitted
from chat.forms import ChatForm
from qr_pair.models import ChatRoom, QRCode


def room(request, room_name, user_id):
    if not is_permitted(room_name=room_name, user_id=user_id):
        raise Http404("user is not permitted")

    user = get_object_or_404(QRCode, id=user_id)
    room_to_join = get_object_or_404(ChatRoom, id=room_name)
    chat_form = ChatForm

    return render(
        request,
        "chat/room.html",
        {
            "room_name": str(room_to_join.id),
            "user_id": str(user.id),
            "history": list(user.chat_history.values()),
            "chat_form": chat_form,
        },
    )


class SendMessage(FormView):
    form_class = ChatForm
    http_method_names = ["post"]

    def form_valid(self, form):
        return JsonResponse({"valid": True})

    def form_invalid(self, form):
        return JsonResponse({"valid": False, "errors": form.errors})

chat/views.py
from django.shortcuts import render

def index(request):
    return render(request, "chat/index.html")

def room(request, room_name):
    return render(request, "chat/room.html", {"room_name": room_name})

app/qr_buddies/templates/chat/room.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/chatroom.css' %}">
{% endblock extra_css %}


{% block content %}
<main class="container-fluid">

    <article id="error">
        Chat socket closed unexpectedly. Please refresh the page.
    </article>

    <section id="chat">
        {# Chat history is displayed here #}
    </section>

    <form id="chat-form" method="POST" action="{% url 'chat:send_message' %}">
        {% csrf_token %}

        <fieldset role="group">
            {{chat_form.message}}
            <input id="chat-message-submit" type="button" value="Send" disabled autocomplete="off">
        </fieldset>
        <small id="invalid-helper">{# Space to display validation errors in #}</small>
    </form>

</main><!--/container-->

{{ room_name|json_script:"room-name" }}
{{ user_id|json_script:"user-id" }}
{{ history|json_script:"history" }}
{% endblock content %}


{% block extra_js %}
<script src="{% static 'js/chat.js' %}"></script>
{% endblock extra_js %}
    