app/administration/urls.py
from django.urls import path

from .views import RoomListView, RoomCreateView, RoomDeleteView

app_name = "administration"
urlpatterns = [
    path("", RoomListView.as_view(), name="room_list"),
    path("rooms/add", RoomCreateView.as_view(), name="create_room"),
    path("rooms/delete/<str:room_pk>/", RoomDeleteView.as_view(), name="delete_room"),
]

app/qr_buddies/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("chat/", include("chat.urls")),
    path("dj-admin/", admin.site.urls),
    path("admin/", include("administration.urls")),
    path("", include("qr_pair.urls")),
]

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

chat/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

qr_buddies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("chat/", include("chat.urls")),
    path('admin/', admin.site.urls),
    path('', include('qr_pair.urls'))
]

app/administration/models.py
# Create your models here.

app/administration/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView

from qr_pair.models import ChatRoom
from django.urls import reverse_lazy


class RoomListView(ListView):
    model = ChatRoom
    template_name = "administration/room_list.html"


class RoomCreateView(CreateView):
    model = ChatRoom
    template_name = "administration/add_room_form.html"
    fields = "__all__"
    success_url = reverse_lazy("administration:room_list")


class RoomDeleteView(DeleteView):
    model = ChatRoom
    template_name = "administration/room_confirm_delete.html"
    pk_url_kwarg = "room_pk"
    success_url = reverse_lazy("administration:room_list")

app/qr_buddies/templates/administration/add_room_form.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1>
        Add room?
    </h1>
    <hr>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Yes">
    </form>
</div>
{% endblock content %}

app/qr_buddies/templates/administration/admin_room_card.html
<article class="card">
    <header>
        <strong>
            {{obj.pk}}
        </strong>

    </header>
    <div role="">
        {% for qr_code in obj.get_qr_codes %}
            {{ qr_code.qr_svg_string|safe }}
        {% endfor %}
    </div>

    <footer role="group">
    {% comment %}links to chat room{% endcomment %}
        {% for qr_code in obj.get_qr_codes %}
        <a role="button" href="{{qr_code.chat_room_link}}">
            QR {{ forloop.counter }}
        </a>
        {% endfor %}
        <a role="button" class="button-delete" href="{% url "administration:delete_room" obj.pk %}">Delete</a>
    </footer>
</article>

app/qr_buddies/templates/administration/room_confirm_delete.html
{% extends 'base.html' %}


{% block content %}

<div class="container">

    <h1>
        Delete Room?
    </h1>


    <form method="post">{% csrf_token %}
        <p>
            Are you sure you want to delete room <strong>"{{ object.pk }}"</strong>?
        </p>
        <hr>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
</div>

{% endblock content %}

app/qr_buddies/templates/administration/room_list.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/admin.css' %}">
{% endblock extra_css %}


{% block content %}
<div class="container">
    <h1>
        Room List
    </h1>
     <a role="button" href="{% url 'administration:create_room' %}">
        + Add Room
    </a>
</div>

<main class="container grid admin-grid">
    {% for obj in object_list %}
        {% include 'administration/admin_room_card.html' %}
    {% endfor %}
</main>
{% endblock content %}